name: Republish

on:
  schedule:
    - cron: '1 03 * * *'  # Run at 3:01 am every day
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub Pages rebuild
        run: |
          curl \
            --request POST \
            --url https://api.github.com/repos/hanaEdonnelly/Dan-Donuts/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN" \
            --header "Accept: application/vnd.github+json"
  env:
    USER_TOKEN: ${{ secrets.USER_TOKEN }}
